<!-- Trigger/Open The Modal -->
<!--<button id="myBtn">Open Modal</button>-->
<!-- The Modal -->
<!--<div id="myModal" class="modal">-->
<!--    <!-- Modal content -->
<!--    <div class="modal-content">-->
<!--        <span class="close">&times;</span>-->
<!--        <p>Some text in the Modal..</p>-->
<!--    </div>-->
<!---->
<!--</div>-->
<?php       if(!$this->getLogIn()==1) {
    ?>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>jQuery UI Dialog - Default functionality</title>
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="/resources/demos/style.css">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script>
            $(function () {
                $("#dialog").dialog();
            });
        </script>
    </head>
    <body>

    <div id="dialog" title="Welcome!">
        <p>Welcome to the Site <?php
            echo $this->popupBlock() . "! We hope you will have a terrific site experience today!";
            ?></p>
    </div>


    </body>
    </html>
<?php
$this->setLogIn();
}
    ?>

