<?php
class Mini_Project_Model_Test extends Mage_Core_Model_Abstract
{
    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('project/test');
    }
}